---
title: "Data loss for EMG and pupillometry in the pilot dataset"
author: "Lucien Bickerstaff"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, warning=F, message=F}
# Seed for reproducibility
set.seed(2025)

# Libraries
library(here)
library(tidyverse)
library(patchwork)
library(gghalves)

source(here("R", "helpers.R"))
source(here("R", "plot_settings.R"))
```



```{r}
pupil_data_loss <- read_csv(here("data", "data_loss", "pupil_pilot_data_loss.csv"))

pupil_data_loss_gavg <- pupil_data_loss %>% 
  group_by(melanopic_edi) %>%
  summarise(Average = mean(Average_inv), 
            SD = sd(Average_inv), 
            .groups = 'drop') %>% 
  rename(Average_inv = Average)

baseline_plot <- ggplot(
  pupil_data_loss %>% dplyr::filter(melanopic_edi == 0),
  aes(x = 0, y = Average_inv)
) +
  geom_half_violin(
      aes(group = melanopic_edi), 
      side = "l", 
      fill = "skyblue", 
      color = NA, 
      alpha = 0.5, 
      adjust = 1, 
      scale  = "count",
      position = position_nudge(x = 0)) +
  geom_jitter(width = 0, height = 0, size = 1, color = "grey60", alpha = 0.6) +
  geom_line(aes(group = Participant), color = "grey60", alpha = 0.1) +
  geom_boxplot(aes(group = melanopic_edi), width = 0.30, outlier.shape = NA, fill = "white", color = "black") +
  coord_cartesian(ylim = c(0, 100), clip = "off") +
  scale_x_continuous(
    breaks = 0,
    labels = "0",
    limits = c(-1, 1),
    expand = c(0, 0)
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0))) +
  labs(
    title = expression(bold("A ") * "Unusable pupillometry data"),
    x = "Melanopic EDI (lx)",
    y = "Data loss (%)"
  ) +
  theme_minimal() +
  theme(
    axis.title.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.x = element_line()
  ) +
  plot_formatting

baseline_plot

nonzero_plot <- ggplot(
  pupil_data_loss %>% dplyr::filter(melanopic_edi > 0),
  aes(x = melanopic_edi, y = Average_inv)
) +
  geom_half_violin(
      aes(group = melanopic_edi), 
      side = "l", 
      fill = "skyblue", 
      color = NA, 
      alpha = 0.5, 
      adjust = 1, 
      scale  = "count",
      position = position_nudge(x = 0)) +
  geom_line(aes(group = Participant), color = "grey60", alpha = 0.1) +
  geom_jitter(aes(group = Participant), size = 1, color = "grey60", alpha = 0.6, width = 0) +
  geom_boxplot(aes(group = melanopic_edi), width = 0.05, outlier.shape = NA, fill = "white", color = "black") +
  geom_line(
    data = pupil_data_loss_gavg %>% dplyr::filter(melanopic_edi > 0),
    aes(x = melanopic_edi, y = Average_inv),
    color = "red",
    linewidth = 1
  ) +
  geom_ribbon(
    data = pupil_data_loss_gavg %>% dplyr::filter(melanopic_edi > 0),
    aes(x = melanopic_edi, ymin = Average_inv - SD, ymax = Average_inv + SD),
    alpha = 0.1,
    inherit.aes = FALSE
  ) +
  coord_cartesian(ylim = c(0, 100),
                  xlim = c(300, 10000),
                  clip = "off") +
  scale_x_log10(breaks = breaks, minor_breaks = minor_breaks) +
  scale_y_continuous(expand = expansion(mult = c(0, 0))) +
  labs(
    x = "Melanopic EDI (lux)",
    y = "Data loss (%)"
  ) +
  theme_minimal() +
  theme(
    axis.title.y = element_blank(),
    axis.text.y  = element_blank(),
    axis.ticks.y = element_blank()
  ) +
  plot_formatting

nonzero_plot

pupil_plot <- baseline_plot + nonzero_plot +
  plot_layout(widths = c(1, 5)) # + plot_annotation(title = "Unusable pupillometry data")

pupil_plot
```

```{r}
emg_data_loss <- read_csv(here("data", "data_loss", "emg_pilot_data_loss.csv"))

emg_plot <- ggplot(emg_data_loss, aes(x = muscle, y = percent_left)) +
  geom_col(width = 0.7, color = "black", fill = "grey70") +
  scale_y_continuous(
    limits = c(0, 100),
    breaks = seq(0, 100, 25),
    expand = expansion(mult = c(0, 0.02))
  ) +
  scale_y_continuous(expand = expansion(mult = c(0, 0))) +
  coord_cartesian(ylim = c(0, 100)) +
  labs(
    x = "Muscle",
    y = "Data loss (%)",
    title = "Unusable EMG datasets"
  ) +
  theme_minimal(base_size = 11) +
  theme(
    panel.grid.major.x = element_blank(),
    axis.text.x = element_text(angle = 25, hjust = 1)
  ) +
  plot_formatting

emg_plot
```


```{r}
emg_plot <- emg_plot + 
  labs(title = expression(bold("B ") * "Unusable EMG datasets"))

emg_plot
pupil_plot

plot_all <- (pupil_plot + emg_plot) +
  plot_layout(ncol = 3, widths = c(1, 5, 5)) +
  plot_formatting &
  theme(
    plot.title = element_text(size = 11),  # set once, both panels
    plot.tag   = element_text(size = 11, face = "bold")
  )
plot_all
```

```{r}
save_rds_safe(plot_all, here("outputs", "figures", "rds", "pilot_data_loss.rds"))
formatted_save(here("outputs", "figures", "pilot_data_loss.png"), plot_all)
```

```{r}
sessionInfo()
```
