---
title: "Plotting OO-EMG dose-response curve"
author: "Lucien Bickerstaff"
date: "`r Sys.Date()`"
output: html_document
---


```{r}
# Seed for reproducibility
set.seed(2025)

# Libraries
library(here)
library(tidyverse)
library(data.table)
library(glue)
library(gghalves)
library(patchwork)

# source(here("R", "emg_settings.R"))
source(here("R", "plot_settings.R"))
```

```{r}
emg_data <- read_csv(here("data", "emg_pilot_data.csv"))

# Calculate number of participants for each channel
n_data <- emg_data %>%
  group_by(melanopic_edi, melanopic_edi_log10, channel) %>%
  summarise(participant_count = n_distinct(participant_id)) %>%
  ungroup() %>%
  distinct() # Remove duplicates
```

```{r}
# --- Build lux_lookup as a compact data.table ---
# Expecting json like: light_conditions: { "1": {"melanopic_edi":..., "photopic_lux":...}, ... }
json_raw   <- jsonlite::fromJSON(here("data", "light_conditions_lookup.json"))
tmp        <- json_raw$light_conditions

lux_lookup <- rbindlist(
  lapply(names(tmp), function(nm) {
    data.table(
      condition     = as.integer(nm),
      melanopic_edi = as.numeric(tmp[[nm]]$melanopic_edi),
      photopic_lux  = as.numeric(tmp[[nm]]$photopic_lux)
    )
  }),
  use.names = TRUE, fill = TRUE
)
setkey(lux_lookup, condition)
```

# Plotting

We start by creating two separate plots (one for the baseline, 0 lux condition, and one for the non-zero conditions), then we combine then using patchwork

```{r}
# Create a plot for each channel
for (chan in unique(emg_data$channel)) {
  # Filter the data for the current channel
  chan <- as.integer(chan)
  muscle <- muscles[chan]
  
  data_channel <- emg_data %>%
    dplyr::filter(channel == chan)
  
  n = n_data %>%
    dplyr::filter(channel == chan) %>%
    dplyr::pull(participant_count)
  
  # ---- Baseline (condition == 0) plot ----

  baseline_data <- emg_data %>%
    dplyr::filter(channel == chan, condition == 0)
  
  baseline_plot <- # ggplot(baseline_data,
  #                          aes(x = factor(1), y = emg_response)) +
                     ggplot(baseline_data,
                           aes(x = melanopic_edi, y = emg_response)) +
  
    # Half violin for distribution
    geom_half_violin( 
      side = "l", 
      fill = "skyblue", 
      color = NA, 
      alpha = 0.5, 
      adjust = 1, 
      scale  = "count",
      position = position_nudge(x = 0)) +
    
    # Jittered raw points
    geom_jitter(size = 1, color = "grey60", alpha = 0.6, width = 0) + # , position = position_nudge(x = 0.05)
    geom_line(color = "grey60", alpha = 0.1) +
    
    # Boxplot summary
    geom_boxplot(width = 0.1, outlier.shape = NA, fill = "white", color = "black") +
  
    geom_hline(yintercept = 100, color = "darkred", alpha = 0.3) +
  
    coord_cartesian(
      ylim = c(45, 2000),
      clip = "off"
    ) +
    
    scale_x_continuous(
      breaks = 0,
      labels = "0",
      limits = c(-1, 1),
      expand = c(0, 0)
    ) +
  
    scale_y_log10(
      breaks = breaks,
      minor_breaks = minor_breaks
    ) +
  
    labs(
      title = glue("Baseline (dark condition)\nEMG activity ({muscle})\nn={n}"),
      x = "Melanopic EDI (lux)",
      y = "EMG signal (% from dark adaptation)"
    ) +
  
    theme_minimal() +
    
    theme(
      panel.grid.minor.x = element_blank(),
      panel.grid.major.x = element_line()   # draws the single x=0 gridline
    ) +
  
    plot_formatting

  saveRDS(
    baseline_plot,
    here("outputs", "figures", "rds", glue("emg_baseline_chan_{chan}.rds"))
  )

  
  # Main plot
  raincould <- ggplot(data_channel %>% dplyr::filter(condition != 0), 
                      aes(x = melanopic_edi, y = emg_response)) +
    # Half violin for distribution
    geom_half_violin(
      aes(group=melanopic_edi), 
      side = "l", 
      fill = "skyblue", 
      color = NA, 
      alpha = 0.5, 
      adjust = 1, 
      scale  = "count",
      position = position_nudge(x = 0)) +
    
    # Jittered raw points
    geom_jitter(size = 1, color = "grey60", alpha = 0.6, width = 0) + # , position = position_nudge(x = 0.05)
    geom_line(aes(group = participant_id),
              color = "grey60", alpha = 0.1) +
    
    # Boxplot summary
    geom_boxplot(aes(group=melanopic_edi), width = 0.025, outlier.shape = NA, fill = "white", color = "black") +
    
    # Linear fit line
    geom_smooth(aes(group = 1), method = "lm", color = "red", se = TRUE, linewidth = 0.5) +
    
    # Horizontal reference line at 100
    geom_hline(yintercept = 100, color = "darkred", alpha = 0.3) +
    
    coord_cartesian(ylim = c(45, 2000), 
                    xlim = c(300, 10000),
                    clip = "off") +
    scale_x_log10(breaks = breaks, minor_breaks = minor_breaks) +
    scale_y_log10(breaks = breaks, minor_breaks = minor_breaks) +
    
    # Axis labels and theming
    labs(title = glue("EMG activity ({muscle})\nn={n}"),
         x = "Melanopic EDI (lux)",
         y = "EMG signal (% from dark adaptation)") +
    theme_minimal() +
    theme(legend.position = "none") +
    plot_formatting
  
  # Save the plot
  saveRDS(raincould, here("outputs", "figures", "rds", glue("emg_raincloud_chan_{chan}.rds")))
}
```

```{r}
# Merge EMG orbicularis oculi baseline + main plots

plot_emg_main <- readRDS(here("outputs", "figures", "rds", glue("emg_raincloud_chan_2.rds"))) +
  coord_cartesian(
    ylim = c(95, 2000), 
    xlim = c(300, 10000),
    clip = "off"
  ) +
  labs(
    title = NULL
  ) +
  theme(
    # Remove y axis from the right plot (keep only on left)
    axis.title.y = element_blank(),
    axis.text.y  = element_blank(),
    axis.ticks.y = element_blank()
  ) 

plot_emg_baseline <- readRDS(here("outputs", "figures", "rds", glue("emg_baseline_chan_2.rds"))) +
  coord_cartesian(
    xlim = c(-0.6, 0.6),
    ylim = c(95, 2000),
    clip = "off"
  ) +
  scale_x_continuous(
    breaks = 0,
    labels = "0",
    expand = c(0, 0)
  ) +
  labs(
    title = NULL
  ) +
  theme(
    # Remove x axis title
    axis.title.x = element_blank()
  )

# Make the two panels look like one figure
# Remove the left plot’s right margin and the right plot’s left margin a bit
plot_emg_baseline <- plot_emg_baseline + theme(plot.margin = margin(5.5, 0, 5.5, 5.5))
plot_emg_main     <- plot_emg_main     + theme(plot.margin = margin(5.5, 5.5, 5.5, 2))

# Arrow / annotation showing dark condition
# plot_emg_baseline <- plot_emg_baseline +
#   annotate("text",
#            x = 0.25,
#            y = 410,
#            label = "(Dark condition)",
#            colour = "black",
#            fontface = "bold",
#            size = 3,
#            vjust = 0) +
#   annotate("segment",
#            x = 0.25, 
#            xend = 0.1,       # ← makes arrow point left
#            y = 400, 
#            yend = 250,   # position slightly below text
#            colour = "black",
#            arrow = arrow(type = "closed", length = unit(0.15, "cm")))

combined <- 
  plot_emg_baseline + labs(title = "Orbicularis oculi EMG response to light") +
  plot_emg_main + plot_layout(widths = c(1, 5))

print(combined)

# Save the plot
formatted_save(here("outputs", "figures", "emg_dose_resp_oo.jpg"), combined, width = 4, height = 4)
saveRDS(combined, here("outputs", "figures", "rds", glue("emg_dose_resp_oo.rds")))
```

```{r}
sessionInfo()
```